### ISSUE TITLE
Not possible to send EOS between reads

### ISSUE THREAD

**Issue by jpaw1** [Geontech/FEI_FileReader#2]
It's currently not possible to send EOS between file reads while looping, it is suppressed until the completion of the last read. Along the lines of the property in the FileReader component, would it be possible to add a property to disable suppressing EOS?

**Comment by patcamwol** [comment]
I've been thinking about this for a few hours, and I'm trying to figure out how this would apply to an actual hardware Device. I may not be thinking outside of the box, but I can't come up with a situation where a single allocation would send an EOS and then create a new stream for the same allocation and start sending data again. 

On the flip side, I can see this being useful for testing how components connected to the device handle an EOS without having to issue multiple allocations.

Right now I see the looping ability as a method to simulate how a hardware device is able to push data indefinitely with a finite-length file.

I'll talk to some people around the office and if you can come up with an example of an FEI Device doing this, I'll go ahead and implement it. Like I said, I may be thinking inside the box.

**Comment by shmahon** [comment]
An EOS can be sent from an FEI device if there is any discontinuity in the data. The behavior, however, is not specified by FEI2.x. Different downstream devices and components will handle it differently.

**Comment by patcamwol** [comment]
All right then, looks like I'll implement it.

**Comment by shmahon** [comment]
Not suggesting that, per se. Just providing use case. Again, some downstream things will handle it. Others won't.
